Candleaf/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework_simplejwt.views import TokenObtainPairView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('auth/', include('djoser.urls')),
    path('api/', include('api.urls')),
    path('api/token/', TokenObtainPairView.as_view(), name = 'token-obtain-pair'),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

api/urls.py
from django.urls import path
from . import views

app_name = 'api'

urlpatterns = [
    path('products/', views.Products.as_view({'get' : 'list'}), name='products'),
    path('products/<int:pk>', views.Products.as_view({'get' : 'retrieve'})),
    path('customers/', views.Customers.as_view({'get' : 'list', 'post' : 'create'})),
    path('customers/<int:pk>/', views.Customers.as_view({'patch' : 'partial_update'})),
    path('orders/', views.Orders.as_view({'get' : 'list', 'post' : 'create'})),
    path('orders/<int:pk>', views.Orders.as_view({'delete' : 'destroy' })),
    path('info/', views.Info.as_view({'get' : 'list', 'post' : 'create'})),
    path('info/<int:pk>', views.Info.as_view({'get' : 'retrieve', 'patch' : 'partial_update'})),
]

website/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

app_name = 'website'
urlpatterns = [
    path('accounts/login', TemplateView.as_view(template_name="registration/login.html"), name='login'),
    path('accounts/signup', TemplateView.as_view(template_name="registration/signup.html"), name='signup'),
    path('products/<int:pk>', views.product, name='product'),
    path('', views.home, name='home'),
    path('cart', TemplateView.as_view(template_name="cart.html"), name="cart"),
    path('checkout', TemplateView.as_view(template_name="checkout.html"), name='checkout'),
    path('shipping', TemplateView.as_view(template_name='shipping.html')),
    path('confirm', TemplateView.as_view(template_name='confirm.html')),
]

api/models.py
from django.db import models
from django.conf import settings
# Create your models here.

class Products(models.Model):
    name = models.CharField(max_length=200)
    price = models.DecimalField(max_digits=7, decimal_places=2)

    def __str__(self):
        return self.name


class Customers(models.Model):
    owner = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    order = models.ManyToManyField(Products, through='Orders')
    status = models.BooleanField(default=False)


    def __str__(self):
        return self.owner.username

class Orders(models.Model):
    customer = models.ForeignKey(Customers, on_delete=models.CASCADE)
    product = models.ForeignKey(Products, on_delete=models.CASCADE)
    number = models.PositiveIntegerField()

    def __str__(self):
        return f'User : ({self.customer.owner.username}) Product: ({self.product.name})'



class Info(models.Model):
    owner = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    phone = models.CharField(max_length=25)
    address = models.CharField(max_length=200)
    postal_code = models.IntegerField()
    state = models.CharField(max_length=100)

website/models.py
from django.db import models

# Create your models here.

api/views.py
from rest_framework.viewsets import ModelViewSet
from rest_framework.permissions import IsAuthenticated
from rest_framework.renderers import JSONRenderer
from . import models
from . import serializers
from rest_framework_simplejwt.authentication import JWTAuthentication



class Products(ModelViewSet):
    queryset = models.Products.objects.all()
    serializer_class = serializers.ProductsSerializer
    renderer_classes = [JSONRenderer]


class Customers(ModelViewSet):
    queryset = models.Customers.objects.all()
    serializer_class = serializers.CustomersSerializer
    permission_classes = [IsAuthenticated]
    authentication_classes = [JWTAuthentication]
    renderer_classes = [JSONRenderer]

    def get_queryset(self):
        return self.queryset.filter(owner=self.request.user)
    
    def get_serializer_context(self):
        return {"user" : self.request.user}


class Orders(ModelViewSet):
    queryset = models.Orders.objects.all()
    serializer_class = serializers.OrdersSerializer
    permission_classes = [IsAuthenticated]
    authentication_classes = [JWTAuthentication]
    renderer_classes = [JSONRenderer]

    def get_queryset(self):
        return self.queryset.filter(customer__owner = self.request.user)



class Info(ModelViewSet):
    queryset = models.Info.objects.all()
    serializer_class = serializers.InfoSerializer
    permission_classes = [IsAuthenticated]
    authentication_classes = [JWTAuthentication]
    renderer_classes = [JSONRenderer]


    def get_queryset(self):
        return self.queryset.filter(owner=self.request.user)

website/views.py
from django.shortcuts import render
from api.models import Products
from django.shortcuts import get_object_or_404

# Create your views here.

def home(request):
    pro = Products.objects.all()
    ctx = {"Products" : pro}
    return render(request, 'home/home.html', ctx)

def product(request, pk):
    pro = get_object_or_404(Products, id=pk)
    ctx = {'product' : pro}
    return render(request, 'product.html', ctx)

website/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Candleaf</title>
<link rel="stylesheet" href="{% static 'css/candleaf.css'%}">
<link rel="stylesheet" href="{% static 'css/all.min.css'%}">
<link rel="stylesheet" href="{% static 'css/normalize.css'%}">
</head>
<body>
    {% include 'main/header.html' %}
   <main>
    {% block content %} {% endblock %}
   </main>
   {% include 'main/footer.html' %}
</body>
</html>

website/templates/candleaf.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Candleaf</title>
<link rel="stylesheet" href="../../static/css/candleaf.css">
<link rel="stylesheet" href="../../static/css/all.min.css">
<link rel="stylesheet" href="../../static/css/normalize.css">
<style>

</style>
</head>
<body>
    <!--Start Header-->
   <header>
    <div class="list-icon">
        <i class="fa-solid fa-bars"></i>
    </div>
    <div class="main-icon">
        <img  class="one" src="../../static/images/products/icon.6e5d1c5d98b7187206cc019288e71fcf.svg">
        <img src="../../static/images/products/wordmark.0c42ab7ebd6cadc552e4ffcc9f7e90c4.svg">
    </div>
    <nav>
        <ul>
            <li><a href="#">Discover</a></li>
            <li><a href="#">About</a></li>
            <li><a href="#">Contact us</a></li>
        </ul>
    </nav>
    <div class="second-icon">
       <a href="#"><i class="fa-regular fa-user"></i></a>
        <a href="#"><i class="fa-solid fa-cart-shopping"></i></a>
    </div>
   </header>
   <!--End Header-->
   <!--Start main element-->
   <main>
    <section class="product">
        <div class="product-box">
          <div class="img-box">
            <img src="../../static/images/products/Sweet Straweberry.png" />
            <p>
              All hand-made with natural soy wax, Candleaf is 
            </p>
            <p>made for your pleasure
              moments.</p>
            <p><i></i>🚚 free shipping</p>
          </div>
          <div class="text-box">
            <h2>Spiced Mint Candleaf®</h2>
            <p>$9.99</p>
            <form>
              <input type="hidden" value="{{price.name}}" name="name" />
              <input type="hidden" value="{{price.price}}" name="price" />
              <div class="Quantity">
                <label>Quantity</label>
                <input type="number" name="number" value="1" min="1"/>
                <button><i class="fa-solid fa-cart-shopping"></i> + Add to cart</button>
              </div>
            </form>
          </div>
        </div>
      </section>
   </main>
   <footer>
    <div class="information">
        <div class="icon-footer">
        <img src="../../static/images/products/footer-logo.6b9a2c80d878270d6a3e26ca369d8f15.svg">
        <p>Your natural candle made for your home and for your wellness</p>
        </div>
        <div class="detalis">
            <div class="discovery">
                <h4>Discovery</h4>
                <p>New season</p>
                <p>Most searched</p>
                <p>Most selled</p>
            </div>
            <div class="about">
                <h4>About</h4>
                <p>Help</p>
                <p>Shipping</p>
                <p>Affiliate</p>
            </div>
            <div class="info">
                <h4>Info</h4>
                <p>Contact us</p>
                <p>Privacy Policies</p>
                <p>Terms & Conditions</p>
            </div>
        </div>
    </div>
   </footer>
</body>
</html>

website/templates/cart.html
{% extends 'base.html'%} {% block content %}
{% load static %}
<style>
  main{
    padding: 0 100px;
  }
</style>
<div class="no-elements">
  <div class="massage">
    <h1>No Products in the Cart</h1>
    <a href="{% url 'website:home' %}">Go and shop</a>
  </div>
</div>
<section class="cart-one">
  <article>
    <h2>Your cart items</h2>
    <p><a href="{% url 'website:home' %}">Back to shopping</a></p>
  </article>
</section>
<section class="cart-two">
  <div class="product-box">
    <div class="item">Product</div>
    <div class="item">Price</div>
    <div class="item">Quantity</div>
    <div class="item">Total</div>
</section>
<section class="section-three">
  <div class="container-product"></div>
</section>
<section class="cart-four">
  <div class="subtotal">
    <div class="information">
      <h2>Subtotal $<span></span></h2>
      <p>Tax and shipping cost will be calculated later</p>
    </div>
    <button class="button">Checkout</button>
  </div>
</section>
<script type="module" src="{% static 'js/cart.js'%}"></script>
{% endblock %}

website/templates/checkout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Candleaf/Checkout</title>
    <link rel="stylesheet" href="{% static 'css/checkout.css'%}">
    <link rel="stylesheet" href="{% static 'css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
</head>

<body>
    <div class="two-column-grid">
        <div class="row">
            <header>
                <img src="{% static 'images/products/icon.6e5d1c5d98b7187206cc019288e71fcf.svg'%}">
                <img src="{% static 'images/products/wordmark.0c42ab7ebd6cadc552e4ffcc9f7e90c4.svg'%}">
            </header>
            <nav>
                <ul>
                    <li>Cart</li>
                    <li>&gt;</li>
                    <li>Shipping</li>
                    <li>&gt;</li>
                    <li>Success</li>
                </ul>
            </nav>
            <main>
                <section class="one">
                    <div class="pre-one">
                        <h3>Contact</h3>
                    </div>
                    <div class="pre-two">
                        <input type="text" placeholder="Mobile phone number" class="phone">
                    </div>
                </section>
                <section class="two">
                    <h3>Shipping</h3>
                    <form method="post">
                        <input type="text" placeholder="First Name", class="first">
                        <input type="text" placeholder="Last Name" class="last">
                        <input type="text" placeholder="Address" class="address">
                        <input type="text" placeholder="Postal Code" class="postal">
                        <select name="state" class="form-control state" >
                            <option value=""> - Select Province/State - </option>
                            <option value="Alabama">Alabama</option>
                            <option value="Alaska">Alaska</option>
                            <option value="Arizona">Arizona</option>
                            <option value="Arkansas">Arkansas</option>
                            <option value="California">California</option>
                            <option value="Colorado">Colorado</option>
                            <option value="Connecticut">Connecticut</option>
                            <option value="Delaware">Delaware</option>
                            <option value="District Of Columbia">District Of Columbia</option>
                            <option value="Florida">Florida</option>
                            <option value="Georgia">Georgia</option>
                            <option value="Hawaii">Hawaii</option>
                            <option value="Idaho">Idaho</option>
                            <option value="Illinois">Illinois</option>
                            <option value="Indiana">Indiana</option>
                            <option value="Iowa">Iowa</option>
                            <option value="Kansas">Kansas</option>
                            <option value="Kentucky">Kentucky</option>
                            <option value="Louisiana">Louisiana</option>
                            <option value="Maine">Maine</option>
                            <option value="Maryland">Maryland</option>
                            <option value="Massachusetts">Massachusetts</option>
                            <option value="Michigan">Michigan</option>
                            <option value="Minnesota">Minnesota</option>
                            <option value="Mississippi">Mississippi</option>
                            <option value="Missouri">Missouri</option>
                            <option value="Montana">Montana</option>
                            <option value="Nebraska">Nebraska</option>
                            <option value="Nevada">Nevada</option>
                            <option value="New Hampshire">New Hampshire</option>
                            <option value="New Jersey">New Jersey</option>
                            <option value="New Mexico">New Mexico</option>
                            <option value="New York">New York</option>
                            <option value="North Carolina">North Carolina</option>
                            <option value="North Dakota">North Dakota</option>
                            <option value="Ohio">Ohio</option>
                            <option value="Oklahoma">Oklahoma</option>
                            <option value="Oregon">Oregon</option>
                            <option value="Pennsylvania">Pennsylvania</option>
                            <option value="Rhode Island">Rhode Island</option>
                            <option value="South Carolina">South Carolina</option>
                            <option value="South Dakota">South Dakota</option>
                            <option value="Tennessee">Tennessee</option>
                            <option value="Texas">Texas</option>
                            <option value="Utah">Utah</option>
                            <option value="Vermont">Vermont</option>
                            <option value="Virginia">Virginia</option>
                            <option value="Washington">Washington</option>
                            <option value="West Virginia">West Virginia</option>
                            <option value="Wisconsin">Wisconsin</option>
                            <option value="Wyoming">Wyoming</option>
                            <option value=""> ---------------- </option>
                            <option value="Alberta">Alberta</option>
                            <option value="British Columbia">British Columbia</option>
                            <option value="Manitoba">Manitoba</option>
                            <option value="New Brunswick">New Brunswick</option>
                            <option value="Newfoundland and Labrador">Newfoundland and Labrador</option>
                            <option value="Nova Scotia">Nova Scotia</option>
                            <option value="Northwest Territories">Northwest Territories</option>
                            <option value="Nunavut">Nunavut</option>
                            <option value="Ontario">Ontario</option>
                            <option value="Prince Edward Island">Prince Edward Island</option>
                            <option value="Quebec">Quebec</option>
                            <option value="Saskatchewan">Saskatchewan</option>
                            <option value="Yukon">Yukon</option>
                        </select>
                    </form>
                </section>
                <footer class="shipping-footer">
                    <a href="{% url 'website:cart'%}">Back to cart</a>
                    <button class="button">Go to shipping</button>
                </footer>
            </main>
        </div>
        <div class="row-two">
            <div class="product-checkout"></div>
            <div class="all">
                <div class="subtotal">
                    <p>Shipping</p>
                    <p>Calculated at the next step</p>
                </div>
                <div class="total">
                    <p>Total</p>
                    <p class="total-price">$<span></span></p>
                </div>
            </div>
        </div>
        <script type="module" src="{% static 'js/checkout.js'%}"></script>
</body>

</html>

website/templates/confirm.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Candleaf</title>
    <link rel="stylesheet" href="{% static 'css/confirm.css'%}">
    <link rel="stylesheet" href="{% static 'css/all.min.css'%}">
    <link rel="stylesheet" href="{% static 'css/normalize.css'%}">
</head>

<body>
        <header>
            <img src="{% static 'images/products/icon.6e5d1c5d98b7187206cc019288e71fcf.svg'%}">
            <img src="{% static 'images/products/wordmark.0c42ab7ebd6cadc552e4ffcc9f7e90c4.svg'%}">
        </header>
        <main>
            <section class="one">
                <i class="fa-regular fa-circle-check"></i>
                <h1>Payment Confirmed</h1>
                <p> Thank you for buying Candleaf. The nature is grateful to you. Now that your order is
                    confirmed it will be ready to ship in 2 days. Please check your inbox in the future for your
                    order updates.</p>
                    <a href="{% url 'website:home'%}">Back to shop</a>
            </section>
        </main>
        <script type="module" src="{% static 'js/confirm.js'%}"></script>
</body>

</html>

website/templates/home/home.html
{% extends 'base.html'%}
{% load static %}
{% block content %}
<section class="home-one">
    <div class="card-bag">
        <i>🌱</i>
        <h3>The nature candle</h3>
        <p>All handmade with natural soy wax, Candleaf is a companion for all your pleasure moments </p>
        <a href="#section-products" id="discovery-btn">Discovery our collection</a>
    </div>
</section>
<section class="section-two">
    <div class="context">
        <h2>Products</h2>
        <p>Order it for you or your beloved ones</p>
    </div>
    <div class="section-products" id="section-products">
        {% for product in Products %}
        <div>
            <a href="{% url 'website:product' product.id %}"><img src="static/images/products/{{product.name}}.png"></a>
            <h4>{{product.name}}</h4>
            <p>{{product.price}}$</p>
        </div>
        {% endfor %}
    </div>
</section>
<!--Start section benefits-->
<section class="section-benefits">
    <div class="benefit-context">
        <h2>Clean and fragrant soy wax</h2>
        <p>Made for your home and for your wellness</p>
        <ul>
            <li><i class="fa-regular fa-circle-check"></i>Eco-susrainable:All recycable materials, 0%CO2 emissions</li>
            <li><i class="fa-regular fa-circle-check"></i></i>Hyphoallergnic:100% natural, human freindly ingredients</li>
            <li><i class="fa-regular fa-circle-check"></i></i>Handmade:All candles are craftly made with love.</li>
            <li><i class="fa-regular fa-circle-check"></i></i>Long burning:No more waste. Created for last long.</li>
        </ul>
        <button>Learn more</button>
    </div>
    <div class="candle-groups">
        <img src="{% static 'images/products/candle_groups.ac0bd1862b0da31d98fe.png'%}">
    </div>
</section>
<!--End section benefits-->
<!--Start testimonials section-->
<section class="testimonials">
<div class="context">
<h2>Testimonials</h2>
<p>Some quotes from our happy customers</p>
</div>
<div class="quotes">
<div class="user-box">
    <img  class="user-img" src="{% static 'images/products/user1.a53d5804a1a1d7cd8234.png'%}">
    <div>
        <span><img src="{% static 'images/products/star.38ca517c73c491c3d955a799b27aaac6.svg'%}"></span>
        <span><img src="{% static 'images/products/star.38ca517c73c491c3d955a799b27aaac6.svg' %}"></span>
        <span><img src="{% static 'images/products/star.38ca517c73c491c3d955a799b27aaac6.svg'%}"></span>
        <span><img src="{% static 'images/products/star.38ca517c73c491c3d955a799b27aaac6.svg'%}"></span>
    </div>
    <p><q>I love it! No more air fresheners</q></p>
    <div class="user-name">Luisa</div>
</div>
<div class="user-box">
    <img class="user-img" src="{% static 'images/products/user2.bb1d41d5b7d50f946946.png'%}">
    <div>
        <span><img src="{% static 'images/products/star.38ca517c73c491c3d955a799b27aaac6.svg'%}"></span>
        <span><img src="{% static 'images/products/star.38ca517c73c491c3d955a799b27aaac6.svg' %}"></span>
        <span><img src="{% static 'images/products/star.38ca517c73c491c3d955a799b27aaac6.svg'%}"></span>
        <span><img src="{% static 'images/products/star.38ca517c73c491c3d955a799b27aaac6.svg'%}"></span>
    </div>
    <p><q>Raccomended for everyone</q></p>
    <div class="user-name">Edoardo</div>
</div>
<div class="user-box">
    <img class="user-img" src="{% static 'images/products/user3.bac4862b982968fde686.png'%}">
    <div>
        <span><img src="{% static 'images/products/star.38ca517c73c491c3d955a799b27aaac6.svg'%}"></span>
        <span><img src="{% static 'images/products/star.38ca517c73c491c3d955a799b27aaac6.svg' %}"></span>
        <span><img src="{% static 'images/products/star.38ca517c73c491c3d955a799b27aaac6.svg'%}"></span>
        <span><img src="{% static 'images/products/star.38ca517c73c491c3d955a799b27aaac6.svg'%}"></span>
    </div>
    <p><q>Looks very natural, the smell is awesome</q></p>
    <div class="user-name">Mart</div>
</div>
</div>
</section>
<section class="popular-product-section">
    <div class="context">
        <h2>Popular</h2>
        <p>Our top selling product that you may like</p>
    </div>
    <div class="section-products">
        {% for product in Products%}
        {% if forloop.counter0 < 4 %}
        <div>
            <a href="{% url 'website:product' product.id%}"><img src="static/images/products/{{product.name}}.png"></a>
            <h4>{{product.name}}</h4>
            <p>{{product.price}}$</p>
        </div>
        {% endif %}
        {% endfor %}
    </div>
</section>
{% endblock %}

website/templates/main/footer.html
{% load static %}
<footer>
  <div class="information">
    <div class="icon-footer">
      <img
        src="{% static 'images/products/footer-logo.6b9a2c80d878270d6a3e26ca369d8f15.svg'%}"
      />
      <p>Your natural candle made for your home and for your wellness</p>
    </div>
    <div class="detalis">
      <div class="discovery">
        <h4>Discovery</h4>
        <p>New season</p>
        <p>Most searched</p>
        <p>Most selled</p>
      </div>
      <div class="about">
        <h4>About</h4>
        <p>Help</p>
        <p>Shipping</p>
        <p>Affiliate</p>
      </div>
      <div class="info">
        <h4>Info</h4>
        <p>Contact us</p>
        <p>Privacy Policies</p>
        <p>Terms & Conditions</p>
      </div>
    </div>
  </div>
</footer>

website/templates/main/header.html
{% load static%}
<header>
  <div class="list-icon">
    <i class="fa-solid fa-bars"></i>
  </div>
  <div class="main-icon">
    <img
      class="one"
      src="{% static 'images/products/icon.6e5d1c5d98b7187206cc019288e71fcf.svg'%}"
    />
    <img src="{% static 'images/products/wordmark.0c42ab7ebd6cadc552e4ffcc9f7e90c4.svg'%}" />
  </div>
  <nav>
    <ul>
      <li><a href="{% url 'website:home'%}">Home</a></li>
      <li><a href="#">About</a></li>
      <li><a href="#">Contact us</a></li>
    </ul>
  </nav>
  <div class="second-icon">
    <a href="{% url 'website:cart'%}"><i class="fa-solid fa-cart-shopping"></i></a>
  </div>
</header>
<script type="module" src="{% static 'js/header.js' %}"></script>

website/templates/product.html
{% extends 'base.html'%} {% block content %}
{% load static %}
<section class="product">
  <div class="product-box">
    <div class="img-box">
      <img src="/static/images/products/{{product.name}}.png" />
      <p>
        All hand-made with natural soy wax, Candleaf is 
        <p>made for your pleasure
          moments.</p>
      </p>
      <p>🚚 free shipping</p>
    </div>
    <div class="text-box">
      <h2>{{product.name}} Candleaf®</h2>
      <p>${{product.price}}</p>
      <form>
        <input type="hidden" value="{{product.id}}" class="id">
        <div class="Quantity">
          <label>Quantity</label>
          <div class="Qun-con">
            <button class="increase">+</button>
            <span class="num">1</span>
            <button class="decrease">-</button>
          </div>
        </div>
        <input type="submit"  value="+ Add to cart" class="button">
        <input type="hidden" name="next" value="{{next}}" />
      </form>
    </div>
  </div>
</section>
<script type="module" src="{% static 'js/product.js' %}"></script>
{% endblock %}

website/templates/shipping.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Candleaf/Shipping</title>
    <link rel="stylesheet" href="{% static 'css/shipping.css'%}">
    <link rel="stylesheet" href="{% static 'css/all.min.css'%}">
    <link rel="stylesheet" href="{% static 'css/normalize.css'%}">
</head>

<body>
    <div class="two-column-grid">
        <div class="row">
            <header>
                <img src="{% static 'images/products/icon.6e5d1c5d98b7187206cc019288e71fcf.svg'%}">
                <img src="{% static 'images/products/wordmark.0c42ab7ebd6cadc552e4ffcc9f7e90c4.svg'%}">
            </header>
            <nav>
                <ul>
                    <li>Cart</li>
                    <li>&gt;</li>
                    <li>Details</li>
                    <li>&gt;</li>
                    <li>Shipping</li>
                    <li>&gt;</li>
                    <li>Payments</li>
                </ul>
            </nav>
            <main>
                <section class="one">
                    <article>
                        <div class="name">Contact</div>
                        <div class="phone"></div>
                    </article>

                    <hr>
                    <article>
                        <div class="name">Ship to</div>
                        <div class="address"></div>
                    </article>
                </section>
                <section class="two">
                    <h3>Shipping method</h3>
                    <article>
                        <div class="strandard">
                            <div> Strandard shipping</div>
                            <div class="free">Free</div>
                        </div>
                    </article>
                </section>
                <footer>
                    <a href="{% url 'website:cart'%}">Back to cart</a>
                    <button class="button">Confirm The Order</button>
                </footer>
            </main>
        </div>
        <div class="row-two">
            <div class="row-second">
            <div class="product-checkout"></div>
            <div class="all">
                <div class="subtotal">
                    <p>Shipping</p>
                    <p>Free shipping</p>
                </div>
                <div class="total">
                    <p>Total</p>
                    <p class="total-price">$<span></span></p>
                </div>
            </div>
            </div>
        </div>
        <script type="module" src="{% static 'js/shipping.js'%}"></script>
</body>

</html>